language: node_js
node_js:
  - '0.10'
  - '0.11'

notifications:
  email: false

deploy:
  provider: npm
  email: me@traviswebb.com
  api_key:
    secure: AtsVq6Uh9ffT0ed4u/JgyuevOC0OHJq3dtQGln6e/aZ+FSpruOilcxxHbNh5TJEf3F2XpOpvGWnZXPSGMTe0K7M5e7LEJ6ViLx8wrZDenHvKE99PEFm8vjDf3kGtVfuBqF0wBLyl1rQC84u9MRKs0ERek/KP8+xXmi63vlgUOe4=
  on:
    repo: tjwebb/sails-backbone-generator
